# Problem 2: Even Fibonacci Numbers
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed n, find the sum of the even-valued terms.

# def fiboEvenSum(n) :
#   a = 1
#   b = 2
#   sum = 0
#   while(a<=n):
#     if(a%2==0):
#       sum+=a
    
#     c = a+b
#     a = b
#     b = c
  
#   return sum

# ===============
# Retrieve the Array (1193)

# t = int(input())

# for _ in range(t):
#     n = int(input())
#     b = list(map(int, input().split()))
#     a = []
#     sumA = sum(b)//(n+1)
#     for i in b:
#         a.append(str(i-sumA))
#     print(" ".join(a))
    
    
    
